---
- hosts: webservers
  become: yes
  become_method: sudo

  tasks:
  - name: Purge Apache 
    apt: name=apache2 state=absent
    notify:
    - Install apache
 
 #- name: ensure apache is running (and enable it at boot)
 #   service: name=apache2 state=started enabled=yes

  handlers:
    - name: Install apache
      apt: name=apache2 state=installed
      notify:
      - Restart apache
    - name: Restart apache
      service: name=apache2 state=restarted enabled=yes






